name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manuális futtatás engedélyezése

jobs:
  quality:
    runs-on: ubuntu-latest
    # Csak akkor fusson, ha a commit üzenetben szerepel [quality] vagy [ci]
    if: contains(github.event.head_commit.message, '[quality]') || contains(github.event.head_commit.message, '[ci]') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint
    
    - name: Format check with Black
      run: black --check --diff .
    
    - name: Type checking with mypy
      run: mypy . || true
    
    - name: Linting with pylint
      run: pylint **/*.py || true