name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manuális futtatás engedélyezése

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # Csak akkor fusson, ha a commit üzenetben szerepel [test] vagy [ci]
    if: contains(github.event.head_commit.message, '[test]') || contains(github.event.head_commit.message, '[ci]') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Python beállítása
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'
    
    - name: Függőségek telepítése
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Linting és tesztelés
      run: |
        # Csak a legfontosabb ellenőrzések
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pytest --verbose

  # Csak pull request-eknél futó teljes teszt
  full-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Python beállítása ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Függőségek telepítése
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Teljes tesztelés
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
        pytest --verbose